### ISSUE TITLE
Can't render nested fenced code blocks

### ISSUE THREAD

**Issue by bennypowers** [forem/forem#12060]
Works on Github and other markdownables.

e.g.:

``````markdown
```html
<p>hi</p>
```
``````

<img width="829" alt="Screen Shot 2020-12-29 at 11 01 37" src="https://user-images.githubusercontent.com/1466420/103272327-3f0af600-49c5-11eb-8db6-b0f4cc09f9ed.png">

_Originally posted by @bennypowers in https://github.com/forem/forem/issues/6673#issuecomment-752002732_

**Comment by rhymes** [comment]
Hi @bennypowers, thanks again for taking this from Twitter to the repo so we can properly keep track of it!

**Comment by ccoVeille** [comment]
The problem persists 3 years later

https://github.com/forem/forem/discussions/20900

Is there anything planned?

**Comment by FrancisTRdev** [comment]
@mikeydorje @benhalpern Will work on this issue! Also, @ccoVeille If you are still around, let me know!

**Comment by ccoVeille** [comment]
Hi

I'm no longer using forem.

But I'm still around 😁

**Comment by FrancisTRdev** [comment]
@ccoVeille Sounds good! Just letting you know this is being worked on :D

**Comment by FrancisTRdev** [comment]
@mikeydorje Issue still being worked on. Feel free to assign me to the issue if possible mike!

**Comment by FrancisTRdev** [comment]
Hey @ccoVeille! I know your not around on Forem, but a quick question on this issue.


**Assuming you still know the context. I would assume the issue is the rendering issue where if I have this:**

<img width="106" height="131" alt="Image" src="https://github.com/user-attachments/assets/d635b3fe-9d23-42dd-a667-bb23599addfc" />


**I would get this:**

````
```shell
date
```
````


However, it seems that the issue is resolved. Can you confirm if this is the output you are concern of? @mikeydorje @ccoVeille 

<img width="272" height="146" alt="Image" src="https://github.com/user-attachments/assets/6833b21e-71bf-45d4-9044-92d0d1b73b20" />

**Comment by ccoVeille** [comment]
@FrancisTRAlt 

Exactly.

It was the fact using this

`````markdown
````markdown
```shell
date
```
````
`````

Would be rendered as on GitHub

````markdown
```shell
date
```
````


One thing to consider to check is that, using higher level of escaping should also work

For example


``````markdown
`````markdown
````markdown
```shell
date
```
````
`````
``````

Should be rendered

`````markdown
````markdown
```shell
date
```
````
`````

**Comment by ccoVeille** [comment]
My need on forem was to be able to document how to using markdown quote block, and I needed to be able to quote it with 5 back ticks to show off what 4 back ticks would do with a 3 back ticks

**Comment by FrancisTRdev** [comment]
Thanks @ccoVeille! It seems to be working as intended:

<img width="234" height="227" alt="Image" src="https://github.com/user-attachments/assets/16e59adb-7e63-4826-8af0-b93c3829d16c" />

Unless there is some other issue I am not aware of, the issue would be close. Do let me know if otherwise.

**Comment by ccoVeille** [comment]
Then I think it's OK 👍

I'm not the one who opened the issue, but I think you, guys, can close it.

For my understanding, was it fixed because you worked on it, or was it fixed in the past years ?

Is there a commit reference for this change?

Thanks

**Comment by FrancisTRdev** [comment]
@ccoVeille I think at some point someone fixes it, though I am not sure which commit specifically fixes this issue. To be fair, I thought the issue persist because this issue was open for some time now. I haven't got to work on this issue until...today and notice it's already been fixed. Unless @benhalpern @mikeydorje can track down the issue, it's out of my hands basically. I am just an normal contributor lol.

Feel free to close it @mikeydorje!
