### ISSUE TITLE
Users can't delete or edit listings once they've been created

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#12170]
**Describe the bug**

Users on our community - https://www.clusteremployment.com, are unable to edit or delete listings after they've been posted.

**To Reproduce**

1. Go to https://www.clusteremployment.com
2. Create and publish a community listing
3. Click user profile, click dashboard then click listings on the bottom left side of the screen
4. Click edit or delete on existing listings
5. See error

**Expected behavior**

The ability to edit and delete published listings

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10 Home 64-bit (10.0, Build 19042)
- Browser, version: Google Chrome Version 87.0.4280.88 (Official Build) (32-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by cmgorton** [comment]
Hey @AdekunleA thank you for bringing this up. This is a known issue that should be fixed with PR #12098. Can you try clearing your cache and seeing if you can edit or delete a listing. I just tried on my account and it works for me know.

**Comment by cmgorton** [comment]
I apologize @AdekunleA. Looks like this may not be working for other Forems just yet. We are talking internally about this and I will let you know as soon as the previous mentioned PR is deployed to all instances.

**Comment by AdekunleA** [comment]
No problem at all @cmgorton , appreciate the reply!

**Comment by cmgorton** [comment]
Hey @AdekunleA 👋. This should be fixed now. Could you confirm if you are able to edit or delete listings on your community Forem?

**Comment by AdekunleA** [comment]
Hello @cmgorton, I just checked it on different browsers (I cleared cache/cookies and all), I'm still not able to edit or delete listings.

**Comment by cmgorton** [comment]
I believe this was addressed internally with cluster employment @AdekunleA. 
Sorry to ping you again on this but could you try clearing your cache and then editing or deleting a listing again?

**Comment by AdekunleA** [comment]
Hello @cmgorton, no worries at all, I appreciate you reaching out on this issue!

I just cleared the cache and tried it again (on both Chrome and Opera), still not able to edit/delete a listing.

The action works when I click the link through 'Inspect Element', but for some reason, clicking the button doesn't seem to fire the link.

**Comment by cmgorton** [comment]
Thank you for checking! 

_"The action works when I click the link through 'Inspect Element', but for some reason, clicking the button doesn't seem to fire the link"_

Weird! Going to let the team know internally this still isn't working as expected.

**Comment by mikeydorje** [comment]
Closing as stale.

Listings have since been deprecated, and this issue hasn’t had activity since Jan 2021.

If this issue persists on current DEV or your instance, please reopen with updated details/reproduction steps.
