### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by jbolle** [forem/forem#12544]
**Describe the bug**

I created an account via Github connect and I'm unable to access the website when I'm logged. I'm redirected to https://dev.to/onboarding?referrer=https%3A%2F%2Fdev.to%2Fenter and I have a blank page.

**To Reproduce**

1. Create an account with Github
2. Log in to Dev.to

**Expected behavior**

Access the homepage.

**Screenshots**

![console](https://user-images.githubusercontent.com/11540826/106643733-6fc4e900-658a-11eb-9818-ff958730472d.png)

**Desktop (please complete the following information):**

- OS, version: MacOs 10.13.6 
- Browser, version: Chrome 88.0.4324.96

**Comment by cmgorton** [comment]
Hey @jbolle we just pushed a fix for this issue. 
https://github.com/forem/forem/pull/12541

Could you try clearing your cache and logging back in?

**Comment by jbolle** [comment]
Thanks for your reply @cmgorton. 

I tried but I'm still facing the same issue unfortunately.

**Comment by cmgorton** [comment]
Thank you for checking @jbolle . One of our engineers said they used an incognito tab and was able to sign up with GitHub. Would you be willing to try that and see if it works so we can narrow down this bug?

**Comment by jbolle** [comment]
I already tried this but the result is exactly the same. 
By the way I just remembered something that could help. Before create an account with Github, I tried to sign up by email (the same I use for my Github account) but I got an error message. So I did it with Github connect. Could it be related?

**Comment by cmgorton** [comment]
@msarit there is some additional context here in @jbolle's comment. Not sure that is helpful to help debug this for them.

**Comment by cmgorton** [comment]
@jacobherrington if you have a moment could you look into this. 
This issue was supposed to be fixed with #12541 
We have had a few people report problems logging in today.

**Comment by ThatGuySam** [comment]
I was having the same issues but it seems to be working for me okay now. 

However, when I got it working I was testing it incognito so I can't say for sure if the fix works without flushing/hard reloading.

**Comment by jbolle** [comment]
Sorry for the late response but I just tried and everything seems to work fine now. 

Thanks @cmgorton !

**Comment by cmgorton** [comment]
Thanks for following up @jbolle. Glad everything is working for you now!
