### ISSUE TITLE
Comment preview button stopped working

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#19290]
**Describe the bug**

The comment "Preview" buttons on the bottom of the article do not respond. Reproduced on the current `main` branch, as well as on dev.to when I tried few minutes ago.

It worked without a problem on my old branch forked on Feb 5, so I guess that this bug was perhaps introduced by #19090.

~~For the new comment field, you can easily get back functionality by adding `onclick="handleCommentPreview(event)"` to the button, but~~ (No, it doesn't work; maybe I saw things) the reply comment field still gets such a JS error.

![Uncaught ReferenceError: handleCommentPreview is not defined at HTMLButtonElement.onclick](https://user-images.githubusercontent.com/84892012/229360738-f23bea2d-2ae6-4108-bcce-4522e8573ba8.png)
**To Reproduce**

1. Open any Forem article
2. Write something in the comment form
3. Press "Preview" button

**Expected behavior**

Should show the preview.

**Screenshots**

Recorded on dev.to (sorry that cursor was not captured):

https://user-images.githubusercontent.com/84892012/229360182-104bb952-986a-464c-9f5b-d4cab73ab4e7.mp4

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: FF 111, GC 111

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by PhilipHow** [comment]
Fixed

**Comment by yheuhtozr** [comment]
@PhilipHow Sorry, but not completely fixed. Go to any article on dev.to and try to _reply_ to any existing comment. I think you can see the preview button not working.
