### ISSUE TITLE
Word wrap in "connect" (chat) fails in narrower widths

### ISSUE THREAD

**Issue by keithrbennett** [forem/forem#5278]
Below a certain window width, text in the chat (https://dev.to/connect) does not wrap. The bug has been identified in Firefox, Chrome, Safari, and Opera. I did not try any other browsers.

**To Reproduce**

1. Open https://dev.to/connect in any browser (or go to the dev.to site and click the paper airplane icon).
2. Find a conversation that has any lines long enough to wrap.
3. Drag the right edge of the window leftwards. Beyond a certain point the text will fail to wrap.

**Expected behavior**

Text should wrap regardless of the window width unless a word is too long to fit on a line.

**Screenshots**

Correct behavior:

![correct-wrap](https://user-images.githubusercontent.com/28410/71569967-4030eb00-2b05-11ea-8ddd-1d18e6835778.png)

Incorrect behavior:

![failed-wrap](https://user-images.githubusercontent.com/28410/71569971-46bf6280-2b05-11ea-8890-7e37dfa2e8ac.png)

**Desktop (please complete the following information):**

- OS: Mac OS Mojave
- Browser: Firefox, Chrome, Safari, Opera (up to date as of 2019-12-30)

**Comment by maestromac** [comment]
I just double-checked this and I believe this is resolved. Let me know if otherwise.

**Comment by keithrbennett** [comment]
@maestromac I just tested it on the public web site using Firefox and Chrome on a Mac. The problem persists. It does wrap correctly part of the way but when one keeps going left there is a point at which it stops wrapping.

**Comment by rhymes** [comment]
@keithrbennett could you provide a GIF or video recording? It'd be extremely helpful. Thank you!

**Comment by keithrbennett** [comment]
I have an .mp4 showing this but cannot upload it here to Github. Let me know if you'd like me to get it to you another way. Here are 2 screenshots, one displaying the wrap correctly, the other showing the error when I drag the right side of the window left to make it more narrow.

![dev-to-word-wrap-ok](https://user-images.githubusercontent.com/28410/77329461-63c69480-6cf4-11ea-9634-ff4844851fb1.png)
![dev-to-word-wrap-error](https://user-images.githubusercontent.com/28410/77329484-6923df00-6cf4-11ea-8802-e4e76118e56b.png)

**Comment by rhymes** [comment]
@keithrbennett interesting! I just tried, in the same connect chat with your message and it doesn't happen to me with Firefox 75.0 beta 6 on macOS 10.14.6

It does happen with Chrome 80 though :(

**Comment by keithrbennett** [comment]
My Firefox was v 74.0 64-bit, Mac OS. Chrome was Version 80.0.3987.149 (Official Build) (64-bit).

**Comment by narender2031** [comment]
I was also tried to reproduce it on Firefox. but this issue is not reproducing locally.

**Comment by keithrbennett** [comment]
I just checked again on a few browsers, including Chrome Version 84.0.4147.89 (on Mac), and I can no longer reproduce the problem. Feel free to close this issue.

**Comment by rhymes** [comment]
Thanks @narender2031 @keithrbennett
